version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/ocorrencias
      SPRING_DATASOURCE_USERNAME: luiz
      SPRING_DATASOURCE_PASSWORD: luiz123
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: ocorrencias
      POSTGRES_USER: luiz
      POSTGRES_PASSWORD: luiz123
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
